/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package infrastructure;

import com.pulumi.Pulumi;
import infrastructure.configuration.Github;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Pulumi.run(context -> {
            new Github().configure(context);
        });
    }
}
